### ISSUE TITLE
Incomplete project bug

### ISSUE THREAD

**Issue by silviavg** [GateNLP/gate-teamware#253]
I have the following problem, after all the annotators complete their tasks, the project remains as incomplete. In the beginning i was thinking that I'm not setting the annotation proportion correctly. 
The way I calculate the proportion is as follows: 
1. I multiply the number of posts by 3 (I want each document to be annotated by 3 people).
2. I use the result to calculate how many posts each annotator should annotate.
3. I calculate what percentage this amount is of the total amount of data to annotate and set it as a proportion.

_**Example:**_ 
I have 40 document and I want every document to be annotated by 3 annotators. Also I have 4 annotators. So:
40 x 3 = 120 total documents 
120/4=30 document per annotator
30/40=0.75 the proportion to be annotated

I used the example above to replicate the bug. I check the proportion for every annotator (it was 30 documents), then all annotators completed their tasks. The project is still incomplete, 7 documents have to be annotated to complete it. Please see _Bug test_.

**Comment by davidwilby** [comment]
Thanks @silviavg we'll take a look at it

**Comment by davidwilby** [comment]
> Please see *Bug test*.

Where is this please?

**Comment by davidwilby** [comment]
I think that what's happening here is that the proportion isn't high enough and this is the limiting factor.

Note that the proportion is the maximum proportion of all the documents that any one annotator can annotate and that is preventing any more annotators from being served new documents.

Can you try increasing the proportion and see if that allows the remaining documents to be served please?

**Comment by twinkarma** [comment]
Hi @silviavg the proportion that you worked out (0.75) is only for the most optimal case and, as you've seen, it does not work out in every project (see explanation below). There are a few things you can do:

* Set the proportion higher (e.g. by 10/20%)
* Don't allow annotators to reject documents
* Recruit more annotators

Annotation tasks are not pre-assigned to annotators, are served to annotators at random, and different annotators will do annotations at different times. This can sometimes result in some annotators having not yet reached the quota but there's no other documents where it's valid for them to annotate (only remaining documents are ones they've annotated or has been annotated by other people). This issue is made worse when allowing annotators to reject documents.

I do believe that we should give better warning when this happens and pre-assigning annotation tasks may be something worth exploring in the future.

**Comment by ianroberts** [comment]
> This can sometimes result in some annotators having not yet reached the quota but there's no other documents where it's valid for them to annotate (only remaining documents are ones they've annotated or has been annotated by other people).

This should be rather less likely to occur now following the implementation of #384 but it's certainly still possible if annotators are allowed to reject documents.
