### ISSUE TITLE
Document how to upgrade 

### ISSUE THREAD

**Issue by johann-petrak** [GateNLP/gate-teamware#380]
Could not find any information about how to upgrade the teamware version when one has the docker-based deployment running on some server.

Also not sure how this works with the docker images and containers:  is it possible to deploy more than once teamware server on a  machine? Is it possible to deploy two servers using different versions of teamware either in parallel or serially switching between them?

**Comment by ianroberts** [comment]
> is it possible to deploy more than once teamware server on a machine? Is it possible to deploy two servers using different versions of teamware either in parallel or serially switching between them?

There's nothing to stop you deploying several copies on the same machine as long as the compose files and associated resources (the `.env` file, the nginx config, etc.) are inside directories that have different names, i.e. `teamware-1/docker-compose.yml` and `teamware-2/docker-compose.yml` is fine but `app1/teamware/docker-compose.yml` and `app2/teamware/docker-compose.yml` is not - the name of the directory that contains the compose file becomes part of the name of the docker network and containers run by that compose stack.

Each stack would have a completely independent postgresql database server.

**Comment by johann-petrak** [comment]
Thank you that may be useful to include in the installation instructions (perhaps together with a warning about installing from within a git repo, if that is still an issue).

**Comment by ianroberts** [comment]
The actual upgrade process _should_ be as simple as changing the image version number in the compose file and re-running `docker compose up`, but I suppose it would be a good idea to do a temporary clean installation of the new version with `get-teamware.sh` and then check for any diffs between the compose files and .env files in case any of the settings in there have changed or there are new environment variables that you need to set.  The database migrations are run as part of the backend container startup so that should handle DB upgrades automatically (but it does mean that you might want to make sure you have an up to date backup before you do this in case it proves necessary to roll the database back).

**Comment by johann-petrak** [comment]
Can confirm that upgrading worked by performing those steps.
